#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const SOURCE_GPKG = resolve(REPO_ROOT, "Philly_Shipyard.gpkg");
const OUTPUT_DIR = resolve(REPO_ROOT, "public/data/shipyard-gis");
const SOURCE_LAYER = "shipyard_geometry";

const EXPORT_FIELDS = [
  "canonical_id",
  "name",
  "feature_type",
  "layer_collection",
  "visible_label",
  "styleClass",
  "shop_code",
  "node_type",
  "station_type",
  "source_canonical_id",
  "target_canonical_id",
  "drawio_edge_id",
  "movement_mode",
];

const GEOMETRY_EXPORTS = [
  {
    fileName: "points.geojson",
    outputName: "points",
    geometryTypes: ["POINT", "MULTIPOINT"],
  },
  {
    fileName: "lines.geojson",
    outputName: "lines",
    geometryTypes: ["LINESTRING", "MULTILINESTRING"],
  },
  {
    fileName: "polygons.geojson",
    outputName: "polygons",
    geometryTypes: ["POLYGON", "MULTIPOLYGON"],
  },
];

const QGIS_MM_TO_CESIUM_PIXEL_SCALE = 3;

// runCommand is a thin wrapper around execFileSync so conversion failures stop
// immediately and show the GDAL or SQLite stderr output that explains why.
function runCommand(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: REPO_ROOT,
    encoding: "utf8",
    stdio: options.stdio ?? ["ignore", "pipe", "inherit"],
  });
}

// runSqliteScalar reads one SQLite value from the GeoPackage. The converter
// uses SQLite only for metadata and style XML; geometry export is left to GDAL.
function runSqliteScalar(sql) {
  return runCommand("sqlite3", [SOURCE_GPKG, sql]).trim();
}

// escapeSqlString makes the geometry-type list safe for the static SQL strings
// generated by this script.
function escapeSqlString(value) {
  return String(value).replaceAll("'", "''");
}

// buildGeometryFilterSql creates the stable SELECT used by ogr2ogr. Keeping
// this explicit preserves only the app-facing fields the Cesium layer needs.
export function buildGeometryFilterSql(geometryTypes) {
  const selectedFields = EXPORT_FIELDS.map((field) => `"${field}"`).join(", ");
  const typeList = geometryTypes
    .map((geometryType) => `'${escapeSqlString(geometryType)}'`)
    .join(", ");

  return [
    `SELECT ${selectedFields}, geom`,
    `FROM ${SOURCE_LAYER}`,
    "WHERE geom IS NOT NULL",
    `AND ST_GeometryType(geom) IN (${typeList})`,
  ].join(" ");
}

// convertGeometryCollection delegates feature geometry conversion to GDAL so
// the repo does not need a custom GeoPackage reader in the browser app.
function convertGeometryCollection(exportConfig) {
  const outputPath = resolve(OUTPUT_DIR, exportConfig.fileName);
  const sql = buildGeometryFilterSql(exportConfig.geometryTypes);

  runCommand(
    "ogr2ogr",
    [
      "-f",
      "GeoJSON",
      outputPath,
      SOURCE_GPKG,
      "-dialect",
      "SQLite",
      "-sql",
      sql,
      "-nln",
      exportConfig.outputName,
      "-lco",
      "RFC7946=YES",
      "-lco",
      "COORDINATE_PRECISION=7",
    ],
    { stdio: "inherit" },
  );

  return outputPath;
}

// decodeXmlAttribute handles the small XML entity set used in the QGIS style
// document so rule filters and labels can be interpreted without extra deps.
function decodeXmlAttribute(value = "") {
  return value
    .replaceAll("&quot;", '"')
    .replaceAll("&apos;", "'")
    .replaceAll("&lt;", "<")
    .replaceAll("&gt;", ">")
    .replaceAll("&amp;", "&");
}

// parseXmlAttributes extracts attributes from a single XML tag. This converter
// only needs tag-level metadata from QGIS rules and symbols, not a full DOM.
export function parseXmlAttributes(tag) {
  const attributes = {};
  const attributePattern = /([A-Za-z_:][\w:.-]*)="([^"]*)"/g;
  let match = attributePattern.exec(tag);

  while (match) {
    attributes[match[1]] = decodeXmlAttribute(match[2]);
    match = attributePattern.exec(tag);
  }

  return attributes;
}

// readSymbolProperties extracts QGIS renderer properties from one symbol block.
// Option and prop entries are duplicated in the source, so later reads simply
// reinforce the same value.
function readSymbolProperties(symbolBody) {
  const properties = {};
  const optionPattern =
    /<Option\b[^>]*\bname="([^"]+)"[^>]*\bvalue="([^"]*)"[^>]*\/?>/g;
  const propPattern = /<prop\b[^>]*\bk="([^"]+)"[^>]*\bv="([^"]*)"[^>]*\/?>/g;
  let optionMatch = optionPattern.exec(symbolBody);

  while (optionMatch) {
    properties[decodeXmlAttribute(optionMatch[1])] = decodeXmlAttribute(
      optionMatch[2],
    );
    optionMatch = optionPattern.exec(symbolBody);
  }

  let propMatch = propPattern.exec(symbolBody);

  while (propMatch) {
    properties[decodeXmlAttribute(propMatch[1])] = decodeXmlAttribute(
      propMatch[2],
    );
    propMatch = propPattern.exec(symbolBody);
  }

  return properties;
}

// parseQgisSymbols creates a symbol-id map from the QGIS RuleRenderer block.
// Rules reference these numeric symbol names when assigning a styleClass.
function parseQgisSymbols(styleQml) {
  const symbols = new Map();
  const symbolPattern = /<symbol\b([^>]*)>([\s\S]*?)<\/symbol>/g;
  let match = symbolPattern.exec(styleQml);

  while (match) {
    const attributes = parseXmlAttributes(match[1]);
    symbols.set(attributes.name, {
      name: attributes.name,
      type: attributes.type,
      properties: readSymbolProperties(match[2]),
    });
    match = symbolPattern.exec(styleQml);
  }

  return symbols;
}

// parseQgisRules resolves styleClass filters to their referenced QGIS symbol.
// The styleClass value is the stable bridge between GeoPackage data and Cesium.
function parseQgisRules(styleQml) {
  const rules = [];
  const rulePattern = /<rule\b[^>]*\/?>/g;
  let match = rulePattern.exec(styleQml);

  while (match) {
    const attributes = parseXmlAttributes(match[0]);
    const styleClassMatch = attributes.filter?.match(/"styleClass"\s*=\s*'([^']+)'/);

    if (attributes.symbol === undefined || !styleClassMatch) {
      match = rulePattern.exec(styleQml);
      continue;
    }

    const geometryMatch = attributes.filter.match(
      /geometry_type\(\$geometry\)\s*=\s*'([^']+)'/,
    );

    rules.push({
      label: attributes.label,
      symbol: attributes.symbol,
      styleClass: styleClassMatch[1],
      geometryType: geometryMatch?.[1],
    });
    match = rulePattern.exec(styleQml);
  }

  return rules;
}

// parseQgisColor converts QGIS RGBA strings into both array and CSS forms. The
// CSS form can be passed directly to Cesium.Color.fromCssColorString at runtime.
export function parseQgisColor(value, fallback = "255,255,255,255") {
  const parts = String(value || fallback)
    .split(",")
    .map((part) => Number(part.trim()));
  const [red = 255, green = 255, blue = 255, alpha = 255] = parts;
  const normalizedAlpha = Math.max(0, Math.min(alpha / 255, 1));

  return {
    rgba: [red, green, blue, alpha],
    css: `rgba(${red}, ${green}, ${blue}, ${Number(normalizedAlpha.toFixed(4))})`,
  };
}

// qgisMillimetersToPixels gives QGIS-authored symbol sizes a practical Cesium
// screen size while preserving relative differences between line and point types.
function qgisMillimetersToPixels(value, fallbackPixels) {
  const millimeters = Number(value);

  if (!Number.isFinite(millimeters) || millimeters <= 0) {
    return fallbackPixels;
  }

  return Math.max(1, Math.round(millimeters * QGIS_MM_TO_CESIUM_PIXEL_SCALE));
}

// buildCesiumStyle translates one QGIS rule/symbol pair into a compact style
// record that the browser can apply without understanding QGIS XML.
function buildCesiumStyle(rule, symbol) {
  const properties = symbol?.properties ?? {};
  const baseStyle = {
    label: rule.label,
    geometryType: rule.geometryType,
    qgisSymbol: rule.symbol,
    qgisSymbolType: symbol?.type,
  };

  if (symbol?.type === "fill") {
    return {
      ...baseStyle,
      fillEnabled: properties.style !== "no",
      fillColor: parseQgisColor(properties.color, "255,255,255,46"),
      outlineColor: parseQgisColor(properties.outline_color, "255,255,255,255"),
      outlineWidthPx: qgisMillimetersToPixels(properties.outline_width, 2),
    };
  }

  if (symbol?.type === "line") {
    return {
      ...baseStyle,
      strokeColor: parseQgisColor(properties.line_color, "83,216,255,255"),
      strokeWidthPx: qgisMillimetersToPixels(properties.line_width, 2),
    };
  }

  return {
    ...baseStyle,
    pointColor: parseQgisColor(properties.color, "83,216,255,255"),
    outlineColor: parseQgisColor(properties.outline_color, "17,24,39,255"),
    outlineWidthPx: qgisMillimetersToPixels(properties.outline_width, 1),
    pointSizePx: qgisMillimetersToPixels(properties.size, 9),
  };
}

// parseQgisStyles is exported for unit tests because it defines the contract
// between the GeoPackage's styleClass values and the Cesium renderer.
export function parseQgisStyles(styleQml) {
  const symbols = parseQgisSymbols(styleQml);
  const rules = parseQgisRules(styleQml);
  const classes = {};

  for (const rule of rules) {
    classes[rule.styleClass] = buildCesiumStyle(rule, symbols.get(rule.symbol));
  }

  return {
    version: 1,
    sourceStyle: "qgis-rule-renderer",
    classes,
  };
}

// readStyleManifest pulls QGIS XML from the GeoPackage and converts it into the
// small JSON style manifest consumed by src/shipyardGisLayer.js.
function readStyleManifest() {
  const styleQml = runSqliteScalar(
    `SELECT styleQML FROM layer_styles WHERE f_table_name = '${SOURCE_LAYER}' ORDER BY useAsDefault DESC, id LIMIT 1;`,
  );

  return parseQgisStyles(styleQml);
}

// readJsonFile keeps generated-output inspection in one place so manifest
// counts are derived from the exact files the browser will fetch.
function readJsonFile(filePath) {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

// incrementCount updates count maps used by the manifest for quick data sanity
// checks after future GeoPackage edits.
function incrementCount(counts, key) {
  const normalizedKey = key || "unknown";
  counts[normalizedKey] = (counts[normalizedKey] ?? 0) + 1;
}

// summarizeGeneratedFeatures records counts by file and by key attributes. This
// gives tests and reviewers a cheap way to catch accidental export loss.
function summarizeGeneratedFeatures(outputPaths) {
  const summary = {
    files: {},
    featureTypes: {},
    layerCollections: {},
    styleClasses: {},
    totalExported: 0,
  };

  for (const [outputName, outputPath] of Object.entries(outputPaths)) {
    const collection = readJsonFile(outputPath);
    const features = collection.features ?? [];
    summary.files[outputName] = features.length;
    summary.totalExported += features.length;

    for (const feature of features) {
      incrementCount(summary.featureTypes, feature.properties?.feature_type);
      incrementCount(
        summary.layerCollections,
        feature.properties?.layer_collection,
      );
      incrementCount(summary.styleClasses, feature.properties?.styleClass);
    }
  }

  return summary;
}

// readSourceBounds preserves the GeoPackage extent for camera authoring and
// tests without requiring browser code to inspect all features at startup.
function readSourceBounds() {
  const row = runSqliteScalar(
    `SELECT min_x, min_y, max_x, max_y, srs_id FROM gpkg_contents WHERE table_name = '${SOURCE_LAYER}' LIMIT 1;`,
  );
  const [west, south, east, north, srsId] = row.split("|").map(Number);

  return { west, south, east, north, srsId };
}

// buildManifest creates a deterministic metadata file for the checked-in
// generated assets. It uses source mtime/hash instead of a conversion timestamp
// so rerunning the command without source changes does not churn the repo.
function buildManifest(outputPaths) {
  const sourceStats = statSync(SOURCE_GPKG);
  const summary = summarizeGeneratedFeatures(outputPaths);
  const sourceFeatureCount = Number(
    runSqliteScalar(`SELECT COUNT(*) FROM ${SOURCE_LAYER};`),
  );
  const nullGeometryCount = Number(
    runSqliteScalar(`SELECT COUNT(*) FROM ${SOURCE_LAYER} WHERE geom IS NULL;`),
  );

  return {
    version: 1,
    source: {
      file: "Philly_Shipyard.gpkg",
      layer: SOURCE_LAYER,
      hashSha256: createHash("sha256")
        .update(readFileSync(SOURCE_GPKG))
        .digest("hex"),
      modifiedAt: sourceStats.mtime.toISOString(),
    },
    bounds: readSourceBounds(),
    counts: {
      sourceFeatures: sourceFeatureCount,
      exportedFeatures: summary.totalExported,
      skippedNullGeometry: nullGeometryCount,
      byFile: summary.files,
      byFeatureType: summary.featureTypes,
      byLayerCollection: summary.layerCollections,
      byStyleClass: summary.styleClasses,
    },
  };
}

// writeJson writes readable generated artifacts so code review can inspect data
// changes after a future GeoPackage refresh.
function writeJson(fileName, value) {
  writeFileSync(
    resolve(OUTPUT_DIR, fileName),
    `${JSON.stringify(value, null, 2)}\n`,
    "utf8",
  );
}

// convertShipyardGpkg is the public conversion entry point used by npm scripts
// and tests. It leaves GitHub Pages with static assets and no runtime GDAL need.
export function convertShipyardGpkg() {
  if (!existsSync(SOURCE_GPKG)) {
    throw new Error(`Missing source GeoPackage: ${SOURCE_GPKG}`);
  }

  rmSync(OUTPUT_DIR, { recursive: true, force: true });
  mkdirSync(OUTPUT_DIR, { recursive: true });

  const outputPaths = {};

  for (const exportConfig of GEOMETRY_EXPORTS) {
    outputPaths[exportConfig.outputName] =
      convertGeometryCollection(exportConfig);
  }

  writeJson("styles.json", readStyleManifest());
  writeJson("manifest.json", buildManifest(outputPaths));
}

// isDirectRun keeps the module importable by Vitest without executing GDAL.
function isDirectRun() {
  return process.argv[1]
    ? resolve(process.argv[1]) === fileURLToPath(import.meta.url)
    : false;
}

if (isDirectRun()) {
  convertShipyardGpkg();
}
