// PhotoLightbox owns the full-screen image expansion UI used by tour photos.
// It creates its DOM once, accepts image payloads from TourManager, and handles
// close behavior through both the close button and Escape key.
export class PhotoLightbox {
  constructor(options = {}) {
    this.document = options.document ?? document;
    this.root = options.root ?? this.document.body;
    this.isOpen = false;
    this.previousFocus = null;
    this.handleKeyDown = this.handleKeyDown.bind(this);
    this.buildDom();
  }

  // buildDom creates semantic overlay controls without requiring static HTML.
  // The overlay title intentionally duplicates the slide title so the left tour
  // panel can be visually covered while the slide context remains available.
  buildDom() {
    this.overlay = this.document.createElement("div");
    this.overlay.className = "photo-lightbox";
    this.overlay.setAttribute("role", "dialog");
    this.overlay.setAttribute("aria-modal", "true");
    this.overlay.setAttribute("aria-hidden", "true");

    this.title = this.document.createElement("h1");
    this.title.className = "photo-lightbox-title";
    this.title.id = "photoLightboxTitle";
    this.overlay.setAttribute("aria-labelledby", this.title.id);

    this.closeButton = this.document.createElement("button");
    this.closeButton.className = "photo-lightbox-close";
    this.closeButton.type = "button";
    this.closeButton.setAttribute("aria-label", "Close expanded image");
    this.closeButton.textContent = "×";
    this.closeButton.addEventListener("click", () => this.close());

    this.image = this.document.createElement("img");
    this.image.className = "photo-lightbox-image";

    this.caption = this.document.createElement("div");
    this.caption.className = "photo-lightbox-caption";

    this.overlay.append(this.title, this.closeButton, this.image, this.caption);
    this.root.appendChild(this.overlay);
  }

  // open renders the selected image. The payload is generated by TourManager so
  // JSON-authored tour data still flows through textContent/attribute setters.
  open(payload) {
    if (!payload?.src) return;

    this.previousFocus = this.document.activeElement;
    this.title.textContent = payload.title ?? "";
    this.caption.textContent = payload.caption ?? payload.alt ?? "";
    this.image.src = payload.src;
    this.image.alt = payload.alt ?? payload.caption ?? "";
    this.overlay.classList.add("is-open");
    this.overlay.setAttribute("aria-hidden", "false");
    this.isOpen = true;
    this.document.addEventListener("keydown", this.handleKeyDown);
    this.closeButton.focus();
  }

  // close hides the overlay and restores focus to the thumbnail control when
  // possible, which keeps keyboard presentation workflows predictable.
  close() {
    if (!this.isOpen) return;

    this.overlay.classList.remove("is-open");
    this.overlay.setAttribute("aria-hidden", "true");
    this.image.removeAttribute("src");
    this.isOpen = false;
    this.document.removeEventListener("keydown", this.handleKeyDown);

    if (this.previousFocus && typeof this.previousFocus.focus === "function") {
      this.previousFocus.focus();
    }

    this.previousFocus = null;
  }

  // handleKeyDown gives presenters the expected Escape shortcut while leaving
  // arrow-key tour navigation on the TourManager document listener.
  handleKeyDown(event) {
    if (event.key !== "Escape") return;

    event.preventDefault();
    this.close();
  }
}
